SELECT CAR.CAR_ID, 
    CAR.CAR_TYPE, 
    CAR.DAILY_FEE * 30 - (CAR.DAILY_FEE * 30 * PLAN.DISCOUNT_RATE / 100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR CAR
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN PLAN
    ON CAR.CAR_TYPE = PLAN.CAR_TYPE
WHERE CAR.CAR_TYPE IN ('세단', 'SUV')
    AND NOT EXISTS (
        SELECT 1
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY HISTORY
        WHERE CAR.CAR_ID = HISTORY.CAR_ID
            AND HISTORY.START_DATE <= '2022-11-30'
            AND HISTORY.END_DATE >= '2022-11-01'
    )
    AND PLAN.DURATION_TYPE = '30일 이상'
    AND CAR.DAILY_FEE * 30 - (CAR.DAILY_FEE * 30 * PLAN.DISCOUNT_RATE / 100) >= 500000
    AND CAR.DAILY_FEE * 30 - (CAR.DAILY_FEE * 30 * PLAN.DISCOUNT_RATE / 100) <= 2000000
ORDER BY FEE DESC, CAR.CAR_TYPE ASC, CAR.CAR_ID DESC

