SELECT 
    HISTORY.HISTORY_ID,
    FLOOR(CASE 
        WHEN DATEDIFF(HISTORY.END_DATE, HISTORY.START_DATE) + 1 < 7
        THEN CAR.DAILY_FEE * (DATEDIFF(HISTORY.END_DATE, HISTORY.START_DATE) + 1)
        WHEN DATEDIFF(HISTORY.END_DATE, HISTORY.START_DATE) + 1 < 30
        THEN CAR.DAILY_FEE * (DATEDIFF(HISTORY.END_DATE, HISTORY.START_DATE) + 1)
            * (
                SELECT 100 - PLAN.DISCOUNT_RATE
                FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN PLAN
                WHERE PLAN.CAR_TYPE = '트럭'
                AND PLAN.DURATION_TYPE = '7일 이상'
            ) / 100
        WHEN DATEDIFF(HISTORY.END_DATE, HISTORY.START_DATE) + 1 < 90
        THEN CAR.DAILY_FEE * (DATEDIFF(HISTORY.END_DATE, HISTORY.START_DATE) + 1)
            * (
                SELECT 100 - PLAN.DISCOUNT_RATE
                FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN PLAN
                WHERE PLAN.CAR_TYPE = '트럭'
                AND PLAN.DURATION_TYPE = '30일 이상'
            ) / 100
        ELSE CAR.DAILY_FEE * (DATEDIFF(HISTORY.END_DATE, HISTORY.START_DATE) + 1)
            * (
                SELECT 100 - PLAN.DISCOUNT_RATE
                FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN PLAN
                WHERE PLAN.CAR_TYPE = '트럭'
                AND PLAN.DURATION_TYPE = '90일 이상'
            ) / 100
    END) AS FEE
FROM CAR_RENTAL_COMPANY_CAR CAR
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY HISTORY
    ON CAR.CAR_ID = HISTORY.CAR_ID
WHERE CAR.CAR_TYPE = '트럭'
ORDER BY FEE DESC, HISTORY.HISTORY_ID DESC