SELECT D.DEPT_ID, 
D.DEPT_NAME_EN,
ROUND(E.SAL, 0) AS AVG_SAL
FROM HR_DEPARTMENT D
JOIN (
    SELECT DEPT_ID,
    AVG(SAL) AS SAL
    FROM HR_EMPLOYEES
    GROUP BY DEPT_ID
    ) AS E ON D.DEPT_ID = E.DEPT_ID
ORDER BY AVG_SAL DESC