SELECT COUNT(*) AS FISH_COUNT, 
MAX(LENGTH) AS MAX_LENGTH, 
FISH_TYPE FROM 
(SELECT IF(LENGTH IS NULL, 10, LENGTH) AS LENGTH, FISH_TYPE FROM FISH_INFO) AS SUBQUERY
GROUP BY FISH_TYPE
HAVING AVG(LENGTH) >= 33
ORDER BY FISH_TYPE ASC